### ISSUE TITLE
on delete parameter missing on user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name=None)

### ISSUE THREAD

**Issue by davidcalle3141** [aaronn/django-rest-framework-passwordless#8] opened 2018-02-22 00:49 UTC
easy fix user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name=None, on_delete=models.CASCADE)

**Comment by MasterKale** [comment] 2018-02-23 05:56
@davidcalle3141 Just a heads up, this issue is a duplicate of Issue #5, which was solved by PR #6.

**Comment by dkdndes** [comment] 2018-02-23 18:46
It is correct it was resolved [here](https://github.com/aaronn/django-rest-framework-passwordless/blob/master/drfpasswordless/models.py#L38) but 

       $ pip install drfpasswordless

installs the previous version with the bug?

**Comment by MasterKale** [comment] 2018-02-23 18:54
Yeah, unfortunately an updated package containing the fix wasn't deployed to PyPI so that's still installing the old version.

If you want to use it with the patch in place you'll have to download the  current `master` branch as a zip file and then drop the **drfpasswordless** folder contained within into your project. I did that last night and can confirm that it works fine. It's not ideal, but right now it's the only way to get the fixed version that works with Django 2.0.

**Comment by aaronn** [comment] 2018-02-25 04:59
Updated on pypi

**Closed by aaronn** 2018-02-25 04:59 UTC
